- holocron/nn/functional.py
- test/test_nn.py
Updated docstrings and added unittests for inplace optional argument
> Updated nn.functional

- holocron/models/__init__.py
- holocron/models/res2net.py
- test/test_models.py
> Fixed HTTP Error of pretrained res2net

- README.md
- docs/source/_static/css/my_theme.css
Updated color scheme of documentations and updated readme
> Updated doc theme

- .circleci/config.yml
- README.md
Cache was saved with different environments which was causing failures.
> Fixes cache restore

- .circleci/config.yml
Switched Github account used for building to bot k2-s0
> chore: Updated CI build to bot

- README.md
- docs/source/optim.rst
- holocron/nn/functional.py
- holocron/optim/radam.py
- holocron/optim/ralars.py
- holocron/optim/wrapper.py
- updating docstrings
- updating readme
> docs: Doc update

- docs/source/utils.rst
- holocron/utils.py
- test/test_utils.py
- adding a module children name resolver
- adding a module summary
- adding corresponding tests
> feat: Added module summary function

- docs/source/nn.functional.rst
- docs/source/nn.rst
- holocron/models/res2net.py
- holocron/models/resnets.py
- holocron/nn/functional.py
- holocron/nn/modules/__init__.py
- holocron/nn/modules/activation.py
- holocron/nn/modules/loss.py
- holocron/ops/boxes.py
- holocron/optim/lamb.py
- holocron/optim/lars.py
- holocron/optim/lr_scheduler.py
- holocron/optim/radam.py
- holocron/optim/ralars.py
- holocron/optim/wrapper.py
- holocron/utils.py
- test/test_nn.py
- adding implementation of focal loss
- adding the corresponding module
> feat: Added implementation of focal loss

- holocron/nn/functional.py
- test/test_nn.py
- fixing the focal loss computation
- adding unit tests for focal loss
> fix: Fixed focal loss computation

- docs/source/nn.functional.rst
- docs/source/nn.rst
- docs/source/optim.rst
- holocron/nn/functional.py
- holocron/nn/modules/__init__.py
- holocron/nn/modules/downsample.py
- test/test_nn.py
- adding functional and module support of concatenated downsampling as described in YOLO9000 paper
> feat: Added concatenated downsampling

- docs/source/conf.py
- docs/source/models.rst
- holocron/models/__init__.py
- holocron/models/darknet.py
- test/test_models.py
- adding a first implementation of Darknet-19
- adding corresponding documentation
- fixing CSS issue in documentation
> feat: Added first draft of Darknet-19

- .github/workflows/doc-deploy.yaml
- .github/workflows/main.yml
- docs/requirements.txt
- adding verbose to sphinx documentation build
- fixing sphinx-rtd-theme versioning to get a consistent CSS
> doc: Fixed documentation CSS issue

- docs/source/models.rst
- holocron/models/darknet.py
- holocron/models/detection/yolo.py
- holocron/nn/__init__.py
- holocron/nn/init.py
- test/test_models.py
- test/test_nn.py
- refactoring darknet model creation
- adding darknet53 implementation from YOLOv3
- adding corresponding documentation
- adding the `holocron.nn.init` module
> feat: Added Darknet-53 implementation

- docs/source/nn.functional.rst
- docs/source/nn.rst
- holocron/nn/functional.py
- holocron/nn/modules/loss.py
- test/test_nn.py
- test/test_optim.py
- adding both functional and module interface for label smoothing cross entropy
- adding corresponding documentation
> feat: Added label smoothing cross entropy loss

- docs/source/index.rst
- docs/source/nn.rst
- docs/source/utils.data.rst
- holocron/nn/modules/loss.py
- holocron/utils/__init__.py
- holocron/utils/data/__init__.py
- holocron/utils/data/collate.py
- test/test_nn.py
- test/test_utils.py
- adding mixup for dataloaders
- adding a loss criterion wrapper with mixup strategy
- updating the documentation
> feat: Added Mixup collate and loss utilities

- .gitignore
- references/classification/README.md
- references/classification/requirements.txt
- references/classification/train.py
- references/clean_checkpoint.py
- adding a reference training script
- adding a checkpoint cleaning script
> feat: Added training reference script

- CONTRIBUTING.md
- docs/source/conf.py
- docs/source/index.rst
- docs/source/installing.rst
- docs/source/nn.rst
- docs/source/ops.rst
- docs/source/optim.rst
- holocron/nn/modules/activation.py
- holocron/nn/modules/downsample.py
- holocron/nn/modules/loss.py
- holocron/ops/boxes.py
- holocron/optim/lamb.py
- holocron/optim/lars.py
- holocron/optim/lr_scheduler.py
- holocron/optim/radam.py
- holocron/optim/ralars.py
- holocron/optim/wrapper.py
- cleaning docstring references
- adding installation instruction in documentation
- adding website referencing via google analytics verification
> docs: Cleaned documentation for pypi release

- .conda/meta.yaml
- .github/workflows/pkg-upload.yaml
- .gitignore
- setup.py
This PR addresses conda workflow issue upon release by:
- fixing conda recipe
- updating package version
> chore: Fixes conda release job

- .flake8
- docs/source/nn.functional.rst
- docs/source/nn.rst
- holocron/nn/functional.py
- holocron/nn/init.py
- holocron/nn/modules/__init__.py
- holocron/nn/modules/conv.py
- test/test_nn.py
This PR introduces normalized Convolutions by:
- adding both the functional and module interfaces
- adding a corresponding unittest
> feat: Added normalized Convolutions

- docs/source/nn.functional.rst
- docs/source/nn.rst
- holocron/nn/functional.py
- holocron/nn/modules/conv.py
- test/test_nn.py
This PR introduces the operations from the AdderNet paper by:
- adding the functional and module interface
> feat: Added implementation of Add2d

- docs/source/nn.rst
- holocron/nn/modules/conv.py
- test/test_nn.py
This PR introduces slim convolutions by:
- adding SlimConv2d module
- adding a specific unittest
> feat: Added implementation of SlimConv

- README.md
- holocron/nn/modules/activation.py
- holocron/nn/modules/loss.py
- holocron/ops/boxes.py
This PR improves the docstrings of:
- focal loss,
- mish and natural logarithm activations,
- distance iou and complete iou losses.
> docs: Updates docstrings to improve documentation

- holocron/optim/lamb.py
- holocron/optim/lars.py
- holocron/optim/radam.py
- holocron/optim/ralars.py
- holocron/optim/wrapper.py
This PR fixes recent changes in Torch inplace operations as detailed in https://github.com/pytorch/pytorch/issues/32861.
> fix: Fixes usage of Tensor inplace operations

- holocron/models/detection/yolo.py
- references/detection/README.md
- references/detection/requirements.txt
- references/detection/train.py
- references/detection/transforms.py
This PR introduces object detection training by:
- adding a reference training script on PASCAL VOC2012
- adding a README for detection training
- refactoring YOLO loss computation
> feat: Added training reference script for object detection

- docs/source/models.rst
- holocron/models/__init__.py
- holocron/models/segmentation/__init__.py
- holocron/models/segmentation/unet.py
- test/test_models.py
This PR introduces semantic segmentation models by:
- adding an implementation of U-Net
> feat: Added U-Net implementation

- docs/source/models.rst
- holocron/models/segmentation/unet.py
- test/test_models.py
This PR adds implementations of UNet variants by:
- adding implementations of Unet+ and Unet++
- switching default upsampling to bilinear upsampling instead of convtranspose
> feat: Added implementations of UNet+ and UNet++

- references/segmentation/README.md
- references/segmentation/requirements.txt
- references/segmentation/train.py
- references/segmentation/transforms.py
This PR adds reference scripts for semantic segmentation training by:
- adding specific transformations
- adding a main training script
- adding a README
> feat: Added training script for semantic segmentation

- holocron/models/detection/yolo.py
- holocron/models/resnets.py
This PR cleans codebase by removing unused imports
> refactor: Cleaned codebase

- docs/source/nn.functional.rst
- docs/source/nn.rst
- holocron/nn/functional.py
- holocron/nn/modules/activation.py
- test/test_nn.py
This PR adds support of Swish activation by:
- adding both the functional and object API for Swish
- adding a corresponding unittest
- adding it to the documentation
> feat: Added swish activation

- docs/source/models.rst
- holocron/models/__init__.py
- holocron/models/resnet.py
- test/test_models.py
This PR introduces a flexible implementation of ResNet models by:
- adding ResNet class and its different versions
- adding it to the documentation
> feat: Added ResNet implementation

- README.md
- docs/source/nn.functional.rst
- docs/source/nn.rst
- holocron/models/resnet.py
- holocron/nn/functional.py
- holocron/nn/modules/activation.py
- test/test_nn.py
This PR improves SiLU/Swish by:
- implementing a memory efficient module
- renaming Swish to SiLU for proper author credits
- updating documentation & README
> feat: Improved Swish/SiLU efficiency

- holocron/models/resnet.py
This PR fixes SEBlock biases and RexBlock strides.
> fix: Fixed ReXNet implementation

- docs/source/models.rst
- holocron/models/resnet.py
- references/classification/README.md
- test/test_models.py
This PR adds more variants of ReXNet models by:
- adding ReXNet 1.3x, 1.5x, 2.2x
> feat: Added variants of ReXNet

- README.md
- docs/source/nn.functional.rst
- docs/source/nn.rst
- holocron/nn/functional.py
- holocron/nn/modules/activation.py
- test/test_nn.py
This PR adds support of Hard Mish activation by:
- adding both the functional and module API
- updating README
> feat: Added support of Hard mish

- README.md
- docs/source/models.rst
- holocron/models/__init__.py
- holocron/models/resnet.py
- holocron/models/rexnet.py
- holocron/models/tridentnet.py
- test/test_models.py
This PR adds support for TridentNet classification model by:
- adding the specific bottleneck and model definition
- updating the documentation
> feat: Added TridentNet support

- docs/source/models.rst
- docs/source/nn.rst
- holocron/models/res2net.py
- holocron/models/resnet.py
- holocron/models/rexnet.py
- holocron/models/tridentnet.py
- holocron/models/utils.py
- holocron/nn/functional.py
- holocron/nn/modules/activation.py
- holocron/nn/modules/downsample.py
- test/test_models.py
- test/test_nn.py
This PR introduces several improvements by:
- adding ResNet50-D
- refactoring ConcatDownsample2d
- adding GlobalAvgPool2d
> feat: Added Resnet50d and improved several layers

- holocron/models/darknet.py
- holocron/models/detection/yolo.py
- holocron/models/segmentation/unet.py
This PR aims at refactoring model definition by:
- using simple pytorch data structure as often as possible (`nn.Sequential` mostly)
- giving more flexibility for model options
> refactor: Refactored model definition for all tasks

- references/classification/train.py
- references/detection/train.py
- references/segmentation/train.py
This PR improves training script by:
- adding flexibility for image size
- setting better default values for arguments
- improved transformation efficiency
> feat: Updated training scripts

- holocron/models/darknet.py
- holocron/models/detection/yolo.py
This PR fixes Darknet architectures by:
- correcting the stem convolutions of Darknet53
- removing biases from intermediate conv
> fix: Fixed Darknet and YOLO architectures

- holocron/models/darknet.py
- references/classification/README.md
This PR updates darknet classification URLs and performance benchmark.
> feat: Updated Darknet pretrained models

- README.md
- docs/source/nn.rst
- holocron/nn/modules/activation.py
- test/test_nn.py
This PR adds support of the funnel activation by:
- adding the `FReLU` activation module
- updating the unittests
- updating the documentation
- updating the README
> feat: Added support of FReLU

- holocron/models/detection/yolo.py
- references/detection/README.md
This PR fixes the passthrough layer of YOLOv2 by adding a channel compression module.
> fix: Fixed passthrough layer of YOLOv2

- README.md
- docs/source/nn.rst
- holocron/nn/functional.py
- holocron/nn/modules/activation.py
- holocron/nn/modules/loss.py
- test/test_nn.py
This PR adds support of Class-balanced loss by:
- implementing a loss wrapper
- fixing weight reshaping
- updating readme
> feat: Added support for class-balanced loss

- references/classification/requirements.txt
- references/classification/train.py
- references/detection/requirements.txt
- references/detection/train.py
- references/requirements.txt
- references/segmentation/requirements.txt
- references/segmentation/train.py
This PR adds the trick from https://github.com/PhilJd/contiguous_pytorch_params to existing training script.
> feat: Added the contiguous param tricks to training scripts

- .conda/meta.yaml
- .github/workflows/main.yml
- README.md
- docs/source/nn.rst
- holocron/nn/modules/downsample.py
- requirements.txt
- setup.py
- test/test_nn.py
This PR adds support of blur pooling using rosswightman [implementation](https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/blur_pool.py)
> feat: Added support of BlurPool2d

- .conda/meta.yaml
- .github/workflows/pkg-upload.yaml
- docs/source/index.rst
- docs/source/trainer.rst
- holocron/__init__.py
- holocron/trainer/__init__.py
- holocron/trainer/core.py
- holocron/trainer/utils.py
- references/classification/train.py
- references/detection/train.py
- references/requirements.txt
- references/segmentation/train.py
- requirements.txt
- setup.py
- test/test_trainer.py
- test/test_utils.py
This PR adds a Trainer object to easily handle task specific trainings.
> feat: Adds support of a Trainer class

- holocron/models/pyconvresnet.py
- holocron/models/rexnet.py
- holocron/models/tridentnet.py
- holocron/nn/modules/dropblock.py
This PR fixes lint checker and refactors a concatenation operation.
> style: Fixed lint and refactored some functions

- docs/source/trainer.rst
- holocron/models/detection/yolo.py
- holocron/nn/functional.py
- holocron/trainer/core.py
- references/classification/train.py
- references/clean_checkpoint.py
- references/detection/train.py
- references/detection/transforms.py
- references/segmentation/train.py
- test/test_models.py
- test/test_nn.py
- test/test_trainer.py
This PR adds support of Trainers for semantic segmentation and object detection, while refactoring the training script accordingly.
> refactor: Refactored training script for segmentation and detection

- docs/source/trainer.rst
- holocron/trainer/core.py
- references/classification/train.py
- references/detection/train.py
- references/detection/transforms.py
- references/segmentation/train.py
This PR fixes the transformations in the detection script and updates the documentation of trainer objects.
> fix: Fixed detection script and improved documentation for trainers

- references/detection/transforms.py
This PR fixes a transformation used for evaluation in the detection script.
> fix: Fixed transformation of detection script

- references/classification/train.py
- references/detection/train.py
- references/segmentation/train.py
This PR fixes the segmentation script imports
> fix: Fixed segmentation script imports

- holocron/ops/boxes.py
This PR fixes a tensor device issue in the penalty term computation.
> fix: Fixed IoU penalty device issue

- README.md
- docs/source/optim.rst
- holocron/optim/__init__.py
- holocron/optim/adabelief.py
- holocron/optim/functional.py
- holocron/optim/radam.py
- holocron/optim/tadam.py
- test/test_optim.py
This PR refactors optimizers and adds support of AdaBelief
> feat: Added support of AdaBelief

- README.md
- docs/source/nn.rst
- holocron/models/detection/yolo.py
- holocron/models/utils.py
- holocron/nn/modules/__init__.py
- holocron/nn/modules/attention.py
- holocron/nn/modules/downsample.py
- test/test_models.py
This PR adds support of attention and blur pooling in conv sequence.
> feat: Integrated Blurpool and attention into conv_sequence

- README.md
- docs/source/nn.rst
- holocron/nn/modules/__init__.py
- holocron/nn/modules/lambda_layer.py
- test/test_nn.py
This PR adds support of Lambda layer using the implementation of https://github.com/lucidrains/lambda-networks
> feat: Added support of Lambda Layer

- .github/workflows/doc-deploy.yaml
- .github/workflows/main.yml
- .github/workflows/pkg-upload.yaml
- holocron/optim/__init__.py
- holocron/optim/functional.py
- holocron/trainer/core.py
- mypy.ini
This PR optimizes the usage of cache between CI jobs and adds a mypy typing verification. See #97
> chore: Optimized cache in CI

- README.md
- docs/source/nn.rst
- holocron/nn/functional.py
- holocron/nn/modules/loss.py
- test/test_nn.py
This PR adds support of the Mutual Channel Loss, corresponding unittests, the documentation entry and the mention in the README.
> feat: Added support of Mutual Channel Loss

- holocron/models/detection/yolo.py
- holocron/models/detection/yolov2.py
- holocron/models/detection/yolov4.py
- holocron/optim/wrapper.py
- test/test_nn.py
This PR fixes compatibility with PyTorch 1.7.0
> fix: Fixed compatibility with pytorch 1.7.0

- .conda/meta.yaml
- .github/workflows/pkg-upload.yaml
- requirements.txt
- setup.py
This PR does the recurrent post-release modifications that follow:
- updates package version
- updates package requirements
- updates conda build job
> chore: Updated package version and build jobs

- holocron/models/sknet.py
- references/classification/README.md
This PR adds a pretrained model for SKNet-50
> feat: Added pretrained URL for SKNet-50

- holocron/models/detection/yolo.py
- references/classification/train.py
- references/detection/train.py
- references/segmentation/train.py
This PR refactors a few layers in YOLO, adds some width/height clipping and adds SGD to the training script options for optimizer.
> feat: Updated training script

- references/classification/README.md
- references/detection/README.md
- references/segmentation/README.md
> docs: Fixed README typo

- holocron/trainer/core.py
- test/test_trainer.py
The classification trainer only works for classifications with 5 or more classes. The purpose of this PR is to make it adaptive
> Adaptative classification trainer

- test/test_trainer.py
This PR refactors the unittest for ClassificationTrainer with fewer than 5 classes
> test: Refactored unittest for ClassificationTrainer

- README.md
- docs/source/optim.rst
- holocron/optim/__init__.py
- holocron/optim/adamp.py
- holocron/optim/functional.py
- test/test_nn.py
- test/test_optim.py
- added implementation of AdamP
- added corresponding unittest
- added entry in documentation
- updated README
> feat: Added implementation of AdamP

- references/classification/train.py
- added support of CIFAR10 & CIFAR100 in the classification training script
Resolves #111
> feat: Added CIFAR to classification training option

- holocron/models/segmentation/unet.py
- holocron/nn/functional.py
- holocron/trainer/core.py
- references/classification/train.py
- references/detection/train.py
- references/segmentation/README.md
- references/segmentation/train.py
- test/test_models.py
- test/test_trainer.py
- added number of parameters in the documentation of segmentation models
- updated UNet to have a model output of the same size as the input's
- fixed weight adjustment in loss computation
- fixed lr_find when the loader has fewer than 100 iterations
> feat: Updated UNet and improved training scripts

- holocron/models/segmentation/unet.py
- holocron/trainer/core.py
- references/classification/train.py
- references/detection/train.py
- references/segmentation/train.py
- references/segmentation/transforms.py
- fixed unet architectures
- improved LR finder method and setup check
- refactored training scripts
- updated transforms interpolation
> fix: Fixed UNet architecture and improved trainer

- holocron/trainer/core.py
This PR simply fixes the console print during training when a checkpoint has been resumed.
> fix: Fixed console print from resume training

- README.md
This PR simply fixes a typo in the README
> docs: Fixed typo in README

- docs/source/_static/js/custom.js
This PR fixes the URL references in the multi-version documentation.
> docs: Fixed multi-version references

- holocron/trainer/core.py
- test/test_trainer.py
This PR improves IoU computation for the segmentation and adds global accuracy metrics.
> feat: Improved Seg IoU computation and segmentation metrics

- holocron/models/segmentation/unet.py
- references/segmentation/train.py
- test/test_models_segmentation.py
- adds a pretrained checkpoint for `unet_rexnet13`
- adds a script argument in the segmentation training to change the loss weight of the background class
> feat: Pretrained params for unet_rexnet13

- CODE_OF_CONDUCT.md
This PR adds a code of conduct to the repo
> docs: Created code of conduct

- .github/workflows/release.yml
- setup.py
This PR separates the source folder from the package index to avoid any issues, and updates the CI release job
> chore: Cleaned package index mixup

- holocron/trainer/core.py
- references/classification/train.py
- references/detection/train.py
- references/segmentation/train.py
- requirements.txt
- setup.py
- test/test_trainer.py
- adds support of AMP for trainers & training recipes
- updates requirements
- adds sample plotting option for classification
- extends unittests
> feat: Added support of AMP to trainers and training scripts

- holocron/models/detection/yolov4.py
- holocron/nn/modules/lambda_layer.py
- references/detection/transforms.py
- references/segmentation/transforms.py
This PR simply removes unused imports and variables
> refactor: Removed unused imports

- docs/source/utils.data.rst
- holocron/utils/data/collate.py
- references/classification/train.py
- test/test_utils.py
- updated mixup implementation
- updated documentation
- updated unittests
- added mixup option in the classification training recipe
> feat: Improved Mixup design and added it to classification recipe

- holocron/nn/functional.py
This PR fixes the influence of `drop_prob` arg on the behaviour of `holocron.nn.DropBlock2d` output.
> fix: Fixed DropBlock2d drop_prob

- holocron/optim/wrapper.py
- test/test_optim.py
- test/test_optim_wrapper.py
- increased the coverage of holocron.optim
- speeded up tests by switching resnet18 to mobilenet_v3_small
- updated docstrings of optim wrappers
> test: Increased coverage of holocron.optim 

- docs/requirements.txt
- docs/source/changelog.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/installing.rst
This PR improves the landing and installation pages of the documentation.
> docs: Improved documentation landing page

- .github/workflows/scripts.yml
- README.md
- scripts/eval_latency.py
- adds a script to evaluate model latency
- adds full benchmark in README
- adds a CI job to validate the script
> docs: Added latency benchmark in the README

- holocron/utils/data/collate.py
- references/segmentation/transforms.py
- scripts/eval_latency.py
- tests/test_nn_loss.py
- tests/test_requirements.py
- removes unused imports, variables and wrappers
> refactor: Removed unused imports, variables and wrappers

- references/classification/train.py
This PR fixes the training script for image classification on CIFAR.
> fix: Fixed classification training script for CIFAR

- holocron/models/detection/yolov4.py
- updates the backbone of YOLOv4
- improves the loss computation
- improves the docstring of YOLOv4
> feat: Updates the backbone & docstring of YOLOv4

- .flake8
- holocron/models/detection/yolo.py
- holocron/models/detection/yolov2.py
- holocron/models/detection/yolov4.py
- holocron/nn/modules/activation.py
- holocron/nn/modules/conv.py
- holocron/nn/modules/loss.py
- holocron/ops/boxes.py
- references/segmentation/train.py
- updates flake8 config to spot unused imports, docstring backslack issues, undefined variables
- updated codebase to match those constraints
> style: Updated flake8 config

- .github/workflows/style.yml
- Makefile
- holocron/trainer/core.py
- holocron/trainer/segmentation.py
- holocron/trainer/utils.py
- tests/test_trainer.py
- tests/test_trainer_utils.py
- updates isort options
- fixed model param freezing
- updated unittest of param freezing
> fix: Fixed param freezing

- holocron/nn/functional.py
- holocron/nn/modules/loss.py
- tests/test_nn_loss.py
This PR simply fixes the arg name of the mutual channel loss
> refactor: Updated arg of MCLoss

- .flake8
- .github/workflows/style.yml
- .isort.cfg
- Makefile
- references/classification/train.py
- references/detection/train.py
- references/segmentation/train.py
- setup.cfg
- fixes the isort job
- updates the flake8 config
- updates the makefile
> ci: Updated isort config and related CI job

- .github/process_commit.py
This PR fixes the script to check whether a given PR is properly labeled.
> ci: Fixed script for PR label

- .github/workflows/pr-labels.yml
This PR fixes the CI job for PR label check
> ci: Fixed CI job for PR labels

- .github/workflows/pr-labels.yml
This PR simply updates the message of PR label check job.
> ci: Updated message of PR label

- .github/workflows/pr-labels.yml
This PR specifies the trigger of the job, and fixes the error message of the PR label job.
> ci: Fixed message & improved trigger

- README.md
- docs/source/nn.functional.rst
- docs/source/nn.rst
- holocron/nn/functional.py
- holocron/nn/modules/loss.py
- tests/test_nn_loss.py
- adds implementation of `DiceLoss`
- updated the documentation & the readme
- adds unittest
> feat: Added Dice Loss implementation

- .github/workflows/docker.yml
- Dockerfile
- Dockerfile-api
- api/README.md
- api/app/config.py
- api/app/main.py
- api/app/routes/classification.py
- api/app/schemas.py
- api/app/vision.py
- api/requirements-dev.txt
- api/requirements.txt
- api/tests/conftest.py
- api/tests/routes/test_classification.py
- docker-compose.yml
- adds a slim dockerfile
- adds a FastAPI boilerplate for image classification
- adds unittests
- adds CI jobs for API unittests and package docker build
> feat: Added FastAPI boilerplate for image classification

- README.md
- docs/source/index.rst
- updates README
- adds Holocron logo in README and documentation
> docs: Updates the README and documentation

- CITATION.cff
- README.md
This PR adds the CITATION.cff file and updates the bibtex ref!
> docs: Added CITATION file

- holocron/models/classification/resnet.py
- holocron/models/utils.py
- holocron/trainer/core.py
- references/classification/train.py
- references/detection/train.py
- references/segmentation/train.py
- tests/test_trainer.py
- fixed resnet50 config
- adds kwargs of `hf_hub_download`
- renamed trainer method `lr_find` to `find_lr` and reflected changes on other scripts
> refactor: Cleaned ref script args

- references/classification/train.py
- references/detection/train.py
- references/segmentation/train.py
This PR simply refactors the way args are parsed for it to work better in notebooks!
> refactor: Updated arg parsing

- docs/source/_static/css/custom_theme.css
- docs/source/conf.py
- docs/source/models.rst
This PR removes logo from sidebar in the documentation, fixes TOC on holocron.models and updates the landing page title size.
> docs: Updated documentation

- README.md
This PR fixes the codacy badge in the README
> docs: Fixed codacy badge

- .github/workflows/style.yml
- Makefile
- api/app/main.py
- api/app/routes/classification.py
- api/tests/conftest.py
- pyproject.toml
- fixed pyproject.toml for mypy & isort
- updates CI jobs and Makefile
- fixed isort for api
> style: Fixed mypy config and updated CI

- Makefile
- README.md
- docs/source/conf.py
- holocron/optim/wrapper.py
- holocron/utils/data/collate.py
- fixes the README badge for documentation
- fixes the command name in the Makefile
- adds a documentation edit button
- fixes docstring examples for the new theme
> docs: Fixed README badge and updated documentation

- .conda/meta.yaml
- .github/workflows/release.yml
- api/pyproject.toml
- docs/build.sh
- docs/source/_static/js/custom.js
- docs/source/changelog.rst
- setup.py
- updates version index
- updates setup.py to add a sanitizer for version index
> chore: Applied post release modifications

- .github/FUNDING.yml
This PR adds a sponsor button to the repository page.
> ci: Added FUNDING button

- holocron/trainer/detection.py
- pyproject.toml
This PR bumps the mypy version and removes some typing ignore.
> style: Bumped mypy version to 0.971 and removes some typing ignores

- references/classification/train.py
- references/segmentation/train.py
This PR refactors the evaluation metric print for object detection and semantic segmentation.
> refactor: Refactored training scripts

- docs/build.sh
- pyproject.toml
This PR fixes the folder cleaning during the multi-version doc build.
> docs: Fixed multi-version build

- docs/source/nn.rst
- holocron/nn/modules/downsample.py
- tests/test_nn_downsample.py
Similarly to GlobalAvgPool2d, this PR adds support for its counterpart that uses maximum as a reduction method. The documentation and the unittests were updated accordingly
> feat: Added support of GlobalMaxPool2d

- docs/source/trainer.rst
- docs/source/utils.rst
- holocron/trainer/core.py
- holocron/utils/misc.py
- references/classification/train.py
- references/detection/train.py
- references/segmentation/train.py
- tests/test_utils.py
- adds a function that plots the distribution of aspect ratio and image side for a dataset to select the optimal one.
- integrates that in the training script
- adds entry in the documentation and unittests
- deprecates `doctr.utils.misc.lr_finder` since it's a duplicate of `doctr.trainer.Trainer.find_lr`
Running the function should yield something like:
Closes #236
> feat: Added image dataset analysis

- holocron/trainer/classification.py
- holocron/trainer/core.py
- holocron/trainer/detection.py
- holocron/trainer/segmentation.py
- references/classification/train.py
- references/detection/train.py
- references/segmentation/train.py
- tests/test_trainer.py
- adds gradient accumulation option to the trainer (over X batches)
- adds the option in the training scripts
- adds unittests and updates the docstrings
Closes #235
> feat: Adds gradient accumulation support to trainers

- .github/verify_labels.py
- holocron/trainer/classification.py
- holocron/trainer/core.py
- references/classification/train.py
- tests/test_trainer.py
- adds method to classification trainer to plot the top losses
- adds unittests
- integrates that into training script
- removes optimizer state saving
- updates show_samples
- updates verify_labels
Closes #241
> feat: Added an option to plot the top losses on the training script

- holocron/trainer/core.py
- references/classification/train.py
- references/detection/train.py
- references/segmentation/train.py
- tests/test_trainer.py
- `Trainer.check_setup` now plots the loss graph instead of returning a boolean
- increases the number of samples displayed by `plot_samples` in the detection training
- updates detection training transformations
- fixes param passing in the detection training
> refactors: Updates trainer check_setup and plot_samples

- holocron/trainer/classification.py
- tests/test_trainer.py
This PR adds support of `plot_loss` trainer method to binary classification tasks and updates the unittests.
> feat: Added plot_loss method to BinaryClassificationTrainer

- api/app/vision.py
- demo/app.py
This PR fixes the resizing of images using PIL in api template & demo.
> fix: Fixed PIL resize in API & demo

- .github/labeler.yml
- .github/workflows/pull_requests.yml
This PR adds an autotriage job to simplify PR management.
> ci: Added autotriage job

- docs/source/models.rst
- holocron/models/classification/convnext.py
- holocron/models/classification/mobileone.py
- holocron/models/utils.py
- holocron/nn/modules/lambda_layer.py
- holocron/optim/adamp.py
- holocron/optim/adan.py
- holocron/optim/lamb.py
- holocron/optim/lars.py
- holocron/optim/ralars.py
- holocron/optim/tadam.py
- holocron/trainer/core.py
- holocron/trainer/utils.py
- fixes enumeration in the documentation
- refactors MobileOne implementation
- fixes import of hf hub
> fix: Fixes huggingface_hub import & updates documentation

- .github/workflows/demo.yml
- demo/app.py
This PR fixes the annoying deprecation warnings popping when running the demo with a recent version of gradio.
> fix: Fixed deprecation warnings of gradio

- .gitignore
- pyproject.toml
- references/README.md
- references/classification/README.md
- references/classification/train.py
- references/detection/README.md
- references/detection/train.py
- references/requirements.txt
- references/segmentation/README.md
- references/segmentation/train.py
- adds the codecarbon config file to gitignore
- moves training requirements to an extra of the project
- adds a training README
- adds codecarbon tracking to all training scripts
Closes #206
> feat: Added codecarbon tracking to training scripts

- .gitignore
- scripts/export_to_onnx.py
- tests/test_models_classification.py
- tests/test_models_detection.py
- tests/test_models_segmentation.py
- adds a script to export models to ONNX
- adds unittest for all models
- updates gitignore to ignore onnx files
Closes #203
> feat: Added ONNX export script and unittests

- holocron/models/checkpoints.py
- holocron/models/classification/convnext.py
- holocron/models/classification/darknet.py
- holocron/models/classification/darknetv2.py
- holocron/models/classification/darknetv3.py
- holocron/models/classification/darknetv4.py
- holocron/models/classification/mobileone.py
- holocron/models/classification/pyconvresnet.py
- holocron/models/classification/repvgg.py
- holocron/models/classification/res2net.py
- holocron/models/classification/resnet.py
- holocron/models/classification/rexnet.py
- holocron/models/classification/sknet.py
- holocron/models/classification/tridentnet.py
- holocron/models/presets.py
- holocron/transforms/interpolation.py
- adds convnext_atto checkpoint
- creates a Checkpoint object
- updates preset datasets
- implements the new checkpoint mechanism for convnext
> feat: Added convnext_atto checkpoint and refactored param loading

- .gitignore
- holocron/trainer/core.py
- references/classification/train.py
- updates the training script for image classification
- updates gitignore
> feat: Improved the training recipe for classification

- .pre-commit-config.yaml
This PR adds new precommit hooks to the project.
> ci: Extends precommit hooks

- references/detection/train.py
- references/segmentation/train.py
This PR organizes script args into groups for training scripts.
> style: Reorganized training script args

- .github/verify_labels.py
- api/tests/conftest.py
- holocron/optim/wrapper.py
- pyproject.toml
- tests/test_trainer.py
This PR updates the minimum versions of PyTorch & Torchvision.
> chore: Bumps torch & torchvision versions

- holocron/nn/functional.py
- tests/test_nn_loss.py
This PR fixes the polyloss for soft targets and adds back the test case for soft targets.
Closes #255
> fix: Fixes Polyloss for soft targets

- .github/collect_env.py
- .github/workflows/style.yml
- .pre-commit-config.yaml
- api/app/vision.py
- holocron/models/checkpoints.py
- holocron/models/classification/convnext.py
- holocron/models/classification/darknetv2.py
- holocron/models/classification/darknetv3.py
- holocron/models/classification/darknetv4.py
- holocron/models/classification/mobileone.py
- holocron/models/classification/repvgg.py
- holocron/models/classification/resnet.py
- holocron/models/classification/rexnet.py
- holocron/models/classification/sknet.py
- holocron/models/detection/yolov4.py
- holocron/models/presets.py
- holocron/models/segmentation/unet.py
- holocron/models/segmentation/unetpp.py
- holocron/models/utils.py
- holocron/nn/functional.py
- holocron/nn/modules/activation.py
- holocron/nn/modules/conv.py
- holocron/nn/modules/downsample.py
- holocron/nn/modules/loss.py
- holocron/ops/boxes.py
- holocron/trainer/classification.py
- holocron/transforms/interpolation.py
- holocron/utils/misc.py
- pyproject.toml
This PR bumps ruff to 0.1.14 & fixes corresponding lint & format issues.
> style: Bumps ruff to 0.1.14

- .github/dependabot.yml
This PR adds dependabot weekly update of the version specifiers.
> ci: Adds dependabot update config

- .github/dependabot.yml
> ci: Fixes package ecosystem in dependabot config

- README.md
This PR updates the badges in the README
> docs: Update the badge in the README

- .github/dependabot.yml
This PR updates the frequency of dependabot bumps
> ci: Updates dependabot frequency

- .github/workflows/push.yml
This PR fixes the build step of the dockerhub push CI job
> ci: Fixes dockerhub job

- .github/workflows/push.yml
This PR fixes the build step of the backend API job.
> ci(push): fix Dockerhub push steps

- .github/workflows/push.yml
This PR fixes the makefile command reference in the docker image publish job
> ci(push): fix docker image push

- .github/workflows/page-build.yml
- README.md
- docs/source/installing.rst
This PR updates the installation instructions for the project
> docs(readme): update installation instructions and badges
