frgfm/Holocron

- holocron/optim/lars.py
Fixes a typo in LARS constructor's arguments
> fix: Fixed LARS argument typo

- .circleci/config.yml
- README.md
- docs/Makefile
- docs/make.bat
- docs/requirements.txt
- docs/source/_static/css/my_theme.css
- docs/source/conf.py
- docs/source/index.rst
- docs/source/models.rst
- docs/source/nn.functional.rst
- docs/source/nn.rst
- docs/source/optim.rst
- docs/source/utils.rst
Added doc generation using Sphinx into CI jobs
> Added Sphinx doc generation

- docs/source/index.rst
- docs/source/ops.rst
- holocron/__init__.py
- holocron/ops/__init__.py
- holocron/ops/boxes.py
- test/test_ops.py
- introducing the `ops` module
- adding implementations of distance iou and complete iou losses
- adding corresponding tests
- adding corresponding docs
> feat: Added Distance-IoU and Complete IoU

- docs/source/models.rst
- holocron/models/__init__.py
- holocron/models/darknet.py
- holocron/models/detection/__init__.py
- holocron/models/detection/yolo.py
- test/test_models.py
- adding more flexibility in Darknet classification model
- adding a first implementation of YOLOv2
- adding corresponding tests
> feat: Added first draft of YOLOv2

- docs/source/models.rst
- holocron/models/darknet.py
- holocron/models/detection/yolo.py
- test/test_models.py
- adding a first draft implementation of Darknet24 & YOLOv1
- adding corresponding tests
- adding corresponding documentation
> feat: Added implementation of YOLOv1

- docs/source/index.rst
- docs/source/utils.rst
- holocron/__init__.py
- holocron/utils/__init__.py
- holocron/utils/misc.py
- requirements.txt
- setup.py
- test/test_utils.py
- adding a `lr_finder` function in the utils module
- adding a corresponding unittest
- adding it to the documentation
> feat: Added a learning rate finder

- .conda/meta.yaml
- .github/workflows/pkg-upload.yaml
- holocron/models/darknet.py
- setup.cfg
- setup.py
- adding pretrained weight URLs for darknet24, darknet19 and darknet53
- adding conda recipe
- adding CI job to publish releases
- updating package version
> feat: Added darknets pretrained weights

- holocron/models/darknet.py
- references/classification/README.md
This PR updated Darknet-53 by:
- updating its pretrained URL with an improved version
- updating classification reference README with new results
> feat: Updated Darknet-53 pretrained URL

- .github/workflows/pkg-upload.yaml
- holocron/models/darknet.py
- references/classification/README.md
This Pr aims at:
- updating pretrained URLs for darknet24 and darknet19
- preventing package upload upon release edits
> feat: Updated Darknet-24 and Darknet-19 pretrained URLs

- holocron/models/detection/yolo.py
- test/test_models.py
This PR fixes YOLO inference and loss computation by:
- fixing GT coordinates (xcenter, ycenter, w, h)
- fixing cell loss contribution
- fixing loss computation when GT is empty
- adding unittest to check behaviour in the above cases
- adding pretrained backbone loading option
- changed classification loss back to strict paper implementation
- updated documentation
> feat: Fixed YOLO inference and loss computation

- holocron/utils/misc.py
This PR fixes constant line breaks on notebook backend by importing tqdm from the auto submodule, as suggested [here](https://github.com/tqdm/tqdm/issues/375).
> fix: Fixed progress bar of LR Finder for other backends

- README.md
- holocron/models/darknet.py
- holocron/models/detection/yolo.py
- holocron/optim/lr_scheduler.py
- references/classification/train.py
- references/detection/train.py
This PR cleans code base using Codacy hints and updates README.
> refactor: Cleaned codebase

- holocron/models/darknet.py
- holocron/models/detection/yolo.py
- references/detection/train.py
This PR adds user flexibility in Darknet and YOLO usage by:
- adding the possibility to specify the normalization layer of Darknets
- added backbone freezing option, which will also convert backbone BN to frozen BN
> feat: Improved Darknet and YOLO flexibility

- README.md
- docs/source/models.rst
- holocron/models/segmentation/unet.py
- test/test_models.py
This PR adds a new variant of UNet by:
- adding an implementation of UNet3+
- adding corresponding unittest
- updating README
> feat: Added implementation of UNet3+

- holocron/nn/functional.py
- references/detection/train.py
- test/test_nn.py
This PR improves the concatenated downsampling operation of YOLO architectures by:
- discarding the channel order and switching to `torch.cat` to increase inference speed
- updating unittest
- updating default object detection argument
> feat: Improved YOLO concatdownsample layer's efficiency

- holocron/nn/modules/conv.py
- requirements.txt
- setup.py
This PR fixes compatibility with the latest pytorch version by:
- updating convolution attribute name
- updating pytorch minimum version requirement
> fix: Fixed compatibility with PyTorch 1.5.1

- README.md
- docs/source/optim.rst
- holocron/optim/__init__.py
- holocron/optim/tadam.py
- test/test_optim.py
This PR adds support of TAdam by:
- adding `holocron.optim.TAdam`
- adding a corresponding unittest
> feat: Added implementation of TAdam

- docs/source/nn.functional.rst
- docs/source/nn.rst
- holocron/nn/functional.py
- holocron/nn/modules/__init__.py
- holocron/nn/modules/dropblock.py
- test/test_nn.py
This PR introduces dropblock by:
- adding functional and module APIs
- adding them to the documentation
> feat: Added DropBlock implementation

- README.md
- docs/source/models.rst
- holocron/models/resnet.py
- test/test_models.py
This PR introduces ReXNet models for image classification by:
- simplifying ResNet architecture layout
- adapting the implementation of https://github.com/clovaai/rexnet of ReXNet
- adding it to the documentation
- updating Readme
> feat: Added support of ReXNet

- docs/source/models.rst
- holocron/models/resnet.py
- test/test_models.py
This PR adds a ReXNet variant and pretained weights by:
- adding rexnet2_0x variant
- adding ImageNet pretrained weights from https://github.com/clovaai/rexnet
> feat: Added Rexnet 2.0x and pretrained weights

- README.md
- docs/source/models.rst
- docs/source/nn.rst
- holocron/models/__init__.py
- holocron/models/pyconvresnet.py
- holocron/models/res2net.py
- holocron/models/resnet.py
- holocron/nn/modules/conv.py
- test/test_models.py
- test/test_nn.py
This PR adds support of pyramidal convolutions by:
- adding PyConv2d implementation
- updating README
> feat: Added implementation of Pyramidal convolution

- holocron/models/darknet.py
- references/classification/README.md
This PR fixes some issues of Darknet53 by:
- fixing autograd when using inplace leaky relu as activations in bottlenecks.
- fixing padding of stem conv of darknet53
> fix: Fixed Darknet53 autograd issue

- holocron/models/detection/yolo.py
- references/classification/train.py
- references/clean_checkpoint.py
- references/detection/train.py
- references/segmentation/train.py
This PR fixes YOLO `backbone_norm_layer` argument by passing it correctly to the backbone and setting the default value to `FrozenBatchNorm2d` when `pretrained_backbone=True`.
> refactor: Added back norm layer flexibility for backbone with YOLO

- holocron/models/detection/yolo.py
This PR fixes and improves YOLO models by:
- moving confidence filtering before NMS to lower computation
- fixing box coordinate conversion
- updating anchors to the ones of VOC computed by paper's author (https://github.com/pjreddie/darknet/blob/master/cfg/yolov2-voc.cfg#L242)
- refactoring forward method
> fix: Fixed coordinate conversion in YOLO

- docs/source/models.rst
- holocron/models/darknet.py
- holocron/models/detection/yolo.py
- holocron/models/resnet.py
- holocron/models/rexnet.py
- holocron/models/tridentnet.py
- references/classification/README.md
- test/test_models.py
This PR updates some classification models as follows:
- removed pre-BN conv weights in ReXNet and updated checkpoints accordingly
- improved CSP implementation efficiency and updated CSPDarknet53 pretrained weights
- added weights of resnet50 and tridentnet50
- YOLOv4 and CSPDarknet53 were switched back to using LeakyReLU and no DropBlock (later versions will include them)
> feat: Fixed CSPDarknet53 and updated pretrained models

- README.md
- docs/source/nn.functional.rst
- docs/source/nn.rst
- holocron/nn/functional.py
- holocron/nn/modules/loss.py
- test/test_nn.py
This PR adds support of the complement cross-entropy loss
> feat: Added support of Complement CE loss

- holocron/models/res2net.py
- test/test_models.py
This PR fixes backprop in res2net and adds unittests to ensure classification models have no issue with backprop.
> fix: Fixed backpropagation in Res2Net

- holocron/models/res2net.py
- references/classification/README.md
This PR adds a pretrained res2net50_26w_4s model and updates the classification leaderboard.
> feat: Added pretrained res2net50_26w_4s

- README.md
- docs/source/models.rst
- docs/source/nn.functional.rst
- docs/source/nn.rst
- holocron/nn/functional.py
- holocron/nn/modules/attention.py
- holocron/nn/modules/downsample.py
- test/test_nn.py
This PR adds support of triplet attention, with a modified implementation of https://github.com/LandskapeAI/triplet-attention/blob/master/MODELS/triplet_attention.py.
> feat: Added support of Triplet Attention

- holocron/models/sknet.py
SKNet models larger than SKNet-50 were wrongly defined.
> fix: Fixed SKNet model definitions

- holocron/ops/boxes.py
As per #112, the current implementation has a typo in the aspect ratio term of the Complete IoU-Loss. This PR fixes that typo
Successfully merging this PR will close #112
> fix: Fixed CIoU aspect ratio term

- holocron/models/repvgg.py
- references/classification/README.md
- added pretrained weights for version A0, A1, A2 and B0 of RepVGG
- Updated classification benchmark accordingly
> feat: Added pretrained versions of RepVGG models

- holocron/nn/modules/loss.py
This PR fixes the weight registering in loss modules.
> fix: Fixed loss weight buffer

- holocron/models/tridentnet.py
- holocron/trainer/core.py
This PR fixes the typing issue with TridentNet
> style: Fixed typing of TridentNet

- holocron/models/utils.py
This PR updates the import of `load_state_dict_from_url` to pytorch (instead of using the legacy mirror from torchvision)
> fix: Updated import of load_state_dict_from_url

- holocron/trainer/core.py
This PR fixes the plot limits for LR Find. The numpy `.argmax` method yields a `numpy.int64` which does not verify the check `isinstance(min_idx, int)` so the scaling was off in most cases.
> fix: Fixed LR Finder plot scaling

- README.md
- docs/source/nn.functional.rst
- docs/source/nn.rst
- holocron/models/darknetv4.py
- holocron/models/detection/yolov4.py
- holocron/models/rexnet.py
- holocron/models/segmentation/unet.py
- holocron/nn/functional.py
- holocron/nn/modules/activation.py
- test/test_nn_activation.py
- deprecate SiLU & Mish now that they are integrated in PyTorch (>=1.9.0)
- updated documentation, unittests and readme accordingly
- adapted implementations using those
> refactor: Removed implementations of nn that are now integrated in PyTorch

- holocron/optim/functional.py
This PR removes functional version of radam and ls_cross_entropy
> refactor: Removed functional legacy elements

- holocron/optim/adabelief.py
- holocron/optim/adamp.py
- holocron/optim/lamb.py
- holocron/optim/ralars.py
- holocron/optim/tadam.py
This PR fixes the error message for sparse gradients in optimizers.
> fix: Fixed error message of optimizers

- holocron/trainer/core.py
- holocron/trainer/utils.py
- mypy.ini
- references/classification/train.py
- references/detection/train.py
- references/segmentation/train.py
- test/test_trainer.py
- adds an option in trainer methods to specify normalization layers' weight decay
- updates unittests
- adds the possibility in training scripts
- updates mypy config
Closes #107
> feat: Added custom weight decay for normalization layers

- holocron/trainer/core.py
This PR simply ensures that the LR & loss recorders always have the same length.
> fix: Fixed LR Find when loss explodes

- holocron/models/darknet.py
- holocron/models/darknetv2.py
- holocron/models/darknetv3.py
- holocron/models/darknetv4.py
- holocron/models/detection/yolo.py
- holocron/models/detection/yolov2.py
- holocron/models/detection/yolov4.py
- holocron/models/pyconvresnet.py
- holocron/models/repvgg.py
- holocron/models/res2net.py
- holocron/models/resnet.py
- holocron/models/rexnet.py
- holocron/models/sknet.py
- holocron/models/tridentnet.py
- holocron/models/utils.py
- references/classification/README.md
- tests/test_models.py
- makes bias addition automatic in `conv_sequence`
- improves darknet24 params
- changes the YOLOv1 head to have a reasonable amount of params
- updates classification benchmark
- updates unittest
> feat: Make bias addition automatic in conv_sequence

- references/detection/train.py
- references/segmentation/train.py
- requirements.txt
- setup.py
- adds possibility to train architectures from torchvision in detection & segmentation training
- avoids unnecessary loss weighting in segmentation training
- fixes the use of MCLoss in segmentation training
- updates Pillow version to avoids issues with RandomCrop for the segmentation training (cf. https://github.com/pytorch/vision/issues/4934)
> fix: Fixes MCLoss and RandomCrop in the segmentation training script

- README.md
This PR simply fixes two typos in the latency benchmark section of the README.
> docs: Fixed latency section of the README

- holocron/trainer/core.py
This PR simply fixes LR plotting in the rare case where the minimum loss is reached on the first iteration.
> fix: Fixed LR find plotting

- holocron/trainer/__init__.py
- holocron/trainer/classification.py
- holocron/trainer/core.py
- holocron/trainer/detection.py
- holocron/trainer/segmentation.py
- fixed isort in `__init__`
- adds an option for safeguard in case the loss isn't finite
- updates trainers' docstrings
> feat: Added finite loss safeguard in trainer

- holocron/models/darknetv3.py
- holocron/models/detection/yolo.py
- holocron/models/detection/yolov2.py
- holocron/models/detection/yolov4.py
- holocron/trainer/core.py
- holocron/trainer/detection.py
- references/detection/train.py
- refactored loss weighting of YOLO
- fixed loss weight, anchor scaling & head initialization of YOLOv2
- fixed classification loss and added contribution ignoring to YOLOv4
- adds feature extraction possibility to DarknetV3
- adds nan tolerance to trainer
- refactored metric printing for detection trainer
- fixed torchvision compatibility of detection training
> fix: Fixed multiple detection training & model issues

- holocron/trainer/core.py
- requirements.txt
- setup.py
- tests/test_trainer.py
- removes the dependency of contiguous params now that PyTorch includes it
- updates dependencies
> refactor: Removed contiguous params since torch>=1.7.0 includes it

- scripts/eval_latency.py
This PR simply replaces `time.time()` with `time.perf_counter()` as it is more recommended for precision latency estimation.
> refactor: Updated timing function for latency eval

- docs/requirements.txt
- docs/source/conf.py
- docs/source/index.rst
- docs/source/notebooks.md
- notebooks/README.md
- setup.py
This PR adds notebook tutorial to the documentation:
- quicktour
- integration with HuggingFace hub
- image classification training
> docs: Added tutorial notebooks

- .github/validate_headers.py
- demo/app.py
- demo/requirements.txt
- setup.py
- extends the scope of headers check
- fixed header of setup.py
- changed demo backend from Pytorch to ONNX using the HF Hub integration
> feat: Switched demo backend to ONNX

- README.md
- docs/source/nn.functional.rst
- docs/source/nn.rst
- holocron/nn/functional.py
- holocron/nn/modules/loss.py
- tests/test_nn_loss.py
- adds functional and module implementations of PolyLoss
- adds it to the documentation and the README
- added dedicated unittests
> feat: Added implementation of PolyLoss

- docs/requirements.txt
- setup.py
This PR fixes sphinx sub-dependencies by pinning jinja2 (cf. https://github.com/readthedocs/readthedocs.org/issues/9038)
> chore: Fixed jinja2 dependency

- .github/workflows/docker.yml
- api/Makefile
- api/app/config.py
- api/app/routes/classification.py
- api/app/vision.py
- api/docker-compose.yml
- api/poetry.lock
- api/pyproject.toml
- pyproject.toml
- removes pytorch and uses ONNX as DL framework for inference in the API
- updates dependencies and functions accordingly
> feat: Switched API backend to ONNX

- pyproject.toml
This PR adds a version specifier to `markdown` to solve https://github.com/ryanfox/sphinx-markdown-tables/issues/36
> docs: Fixed documentation build

- holocron/utils/data/collate.py
- references/classification/train.py
- tests/test_utils.py
- fixes the arg passing of the mixup alpha to the training script
- fixes support for one-hot and binary targets
- extends unittests
> fix: Fixed Mixup for binary & one-hot targets

- holocron/trainer/classification.py
- holocron/trainer/core.py
- holocron/trainer/segmentation.py
- tests/test_trainer.py
- fixes trainer for binary classification when the target is wrongly shaped or doesn't have the good data type
- fixes the evaluation loop of binary classification trainer
- extends unittests
> fix: Fixed BinaryClassificationTrainer

- holocron/trainer/classification.py
This PR fixes the accuracy computation for binary classification.
> fix: Fixed binary classification evaluation

- api/app/config.py
- docs/source/index.rst
- docs/source/transforms.rst
- holocron/__init__.py
- holocron/transforms/__init__.py
- holocron/transforms/interpolation.py
- pyproject.toml
- references/detection/train.py
- references/segmentation/train.py
- setup.py
- tests/test_transforms.py
This PR adds support for two transformations:
- Resize (allows padding)
- RandomZoomOut
Additionally, this adds entries in the documentation and corresponding unittests.
> feat: Added two transforms Resize and RandomZoomOut

- holocron/models/utils.py
- holocron/nn/init.py
- holocron/nn/modules/activation.py
- holocron/trainer/classification.py
- holocron/trainer/core.py
- holocron/trainer/detection.py
- holocron/trainer/segmentation.py
- holocron/trainer/utils.py
- holocron/transforms/interpolation.py
- holocron/utils/data/collate.py
- holocron/utils/misc.py
- tests/test_trainer.py
- tests/test_trainer_utils.py
- tests/test_transforms.py
- changed the output signature of inplace freezing functions to None
- added examples in docstings of most functions
> docs: Added examples in docstrings

- README.md
- docs/source/optim.rst
- holocron/optim/__init__.py
- holocron/optim/adan.py
- holocron/optim/functional.py
- tests/test_optim.py
- adds `holocron.optim.Adan` optimizer
- adds unittest and documentation entry
- adds full update rule in the docstring
- updates the README
> feat: Adds support for Adan optimizer

- docs/source/optim.rst
- holocron/optim/__init__.py
- holocron/optim/adabelief.py
- holocron/optim/adamp.py
- holocron/optim/lamb.py
- holocron/optim/lars.py
- holocron/optim/tadam.py
- tests/test_optim.py
- renames `Lars` and `Lamb` into `LARS` and  `LAMB`
- adds the update rule equations to the docstrings of optimizers to improve the documentation
> docs: Added full update equations of all optimizers

- holocron/models/classification/darknet.py
- holocron/models/detection/yolo.py
- holocron/models/detection/yolov2.py
- references/classification/README.md
- tests/test_models_detection.py
- adds the missing param initialization to DarknetV1
- cleans the loss computation of yolo v1 and v2
- adds detailed unittests for YOLO intermediate operations
> test: Adds extensive unittests for YOLO intermediate ops 

- .github/workflows/scripts.yml
- scripts/eval_latency.py
This PR adds the timing with ONNX to get a better production inference latency estimate.
> feat: Improves latency script by adding ONNX

- demo/requirements.txt
This PR bumps gradio to address the security issue https://github.com/frgfm/Holocron/security/dependabot/18
> chore: Bumps gradio to 4.11.0

- .github/workflows/push.yml
- .github/workflows/style.yml
This PR fixes two issues with the CI:
- the build of the docker for dockerhub push was exporting the requirements.txt to the wrong location
- the precommit hook job was run on the main branch which caused it to fail because of the branch guard
> Fixes dockerhub push and precommit CI job

- .github/workflows/builds.yml
- .github/workflows/tests.yml
- README.md
- api/tests/routes/test_classification.py
- docs/source/optim.rst
- holocron/optim/__init__.py
- holocron/optim/adabelief.py
- holocron/optim/adamp.py
- holocron/optim/ademamix.py
- holocron/optim/lamb.py
- holocron/optim/tadam.py
- references/classification/train.py
- tests/test_models_classification.py
- tests/test_ops.py
- tests/test_optim.py
This PR adds support for AdEMAMix optimizer, as detailed in the paper https://arxiv.org/pdf/2409.03137
> feat(optim): add support of AdEMAMix optimizer

- holocron/optim/adabelief.py
- holocron/optim/adamp.py
- holocron/optim/adan.py
- holocron/optim/ademamix.py
- holocron/optim/wrapper.py
- holocron/trainer/core.py
- pyproject.toml
This PR silences the warnings of mypy, which are incorrect
> style(mypy): silence incorrect typing warnings

- .github/dependabot.yml
This PR adds several dependency checks for Docker, CI actions and python packages.
> ci(dependabot): add automatic checks for several dependencies

- demo/requirements.txt
This PR bumps gradio to 5.0.0 to address security issues with the package.
> build(demo): bump gradio to 5.0.0

- .github/workflows/push.yml
This PR fixes the CI job to publish the documentation to GitHub pages.
> ci(docs): fix python version for documentation build
